# Generated by Django 3.1.7 on 2021-03-22 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('Available_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Available_end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email_id',
            field=models.CharField(max_length=200),
        ),
    ]
