# Generated by Django 3.1.7 on 2021-03-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0003_auto_20210323_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availableslots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interviewer_id', models.CharField(max_length=200)),
                ('candidate_id', models.CharField(max_length=200)),
            ],
        ),
    ]
