# Generated by Django 3.1.7 on 2021-03-24 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0004_availableslots'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlotsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_type', models.CharField(choices=[('IN', 'Interviewer'), ('CA', 'Candidate')], default='IN', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Availableslots',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.AddField(
            model_name='availableslotsmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cand_Reg.usermodel'),
        ),
    ]
