# Generated by Django 3.1.7 on 2021-03-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0006_auto_20210324_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableslotsmodel',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Cand_Reg.usermodel'),
        ),
        migrations.AlterField(
            model_name='availableslotsmodel',
            name='candidate_id',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='availableslotsmodel',
            name='interviewer_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
