# Generated by Django 3.1.7 on 2021-03-24 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0007_auto_20210324_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslotsmodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cand_Reg.usermodel'),
        ),
    ]
