# Generated by Django 3.1.7 on 2021-03-24 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0008_auto_20210324_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availableslotsmodel',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='availableslotsmodel',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Cand_Reg.usermodel'),
        ),
    ]
