# Generated by Django 3.1.7 on 2021-03-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0009_auto_20210324_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslotsmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
