# Generated by Django 3.1.7 on 2021-03-24 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0016_availableslotsmodel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableslotsmodel',
            name='number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Cand_Reg.usermodel'),
        ),
    ]
