# Generated by Django 3.1.7 on 2021-03-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cand_Reg', '0017_auto_20210324_1959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableSlotsModel',
        ),
    ]
